### ISSUE TITLE
Рекурсия

### ISSUE THREAD

**Issue by justnik98** [Sergeydigl3/suai_labs#1]
Рекурсия - не самый лучший выбор, так как достаточно быстро забивает память на стеке и при большом значении _**x**_ может переполниться стек.
https://github.com/Sergeydigl3/suai_labs/blob/4baa6439ea3ac2ccf2f2beca1e089998b0fef984/lab1/lab1_fibon.c#L3-L9

**Comment by Sergeydigl3** [comment]
Мне лень переписывать. Лаба принята. А в идеале нужно, мне кажется, разобраться с указателями и использовать ещё и их.
